# Generated by Django 5.1.3 on 2025-01-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_note_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='password',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
