services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./src:/app/src:rw
      - ./start.sh:/app/start.sh
      - ./src/db.sqlite3:/app/src/db.sqlite3:rw
    
    command: /app/start.sh