# Generated by Django 5.1.3 on 2025-01-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_note_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='signature',
            field=models.CharField(default='', max_length=512),
        ),
    ]
